version: "2.2"

services:
  plugin-run:
    image: plugin:${STACK_VERSION}
    volumes:
      - "/data/lab/plugin/jar"
    user: "0"
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Jakarta
      - JAVA_OPTS=${IFDS_JAVA_OPTS}
      - SERVER_PORT=8080

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.252.6.0/24
          gateway: 10.252.6.1
