version: "2.2"

services:
  plugin-run:
    image: plugin:${STACK_VERSION}
    volumes:
      - ./plugin-jar:/workspace/plugin-jar
      - ./application-dev.yml:/workspace/BOOT-INF/classes/application-dev.yml
    user: "0"
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Jakarta
      - JAVA_OPTS=${IFDS_JAVA_OPTS}
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.252.7.0/24
          gateway: 10.252.7.1
